# SPDX-License-Identifier: MIT
---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
# lint: |
#   set -e
#   yamllint .
#   ansible-lint
driver:
  name: docker
platforms:
  - name: "rhc-${image:-fedora}-${tag:-latest}${TOX_ENVNAME}"
    image: "${namespace:-dustinliddick}/${image:-fedora}:${tag:-latest}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    # exposed_ports:
    #   - 80/udp
    #   - 80/tcp
    # published_ports:/ansible/devel/reference_appendices/config.html
    #   - 0.0.0.0:8888:80/udp
    #   - 0.0.0.0:8888:80/tcp
    privileged: true
    pre_build_image: true
    pull: true
provisioner:
  name: ansible
  playbooks:
    converge: ../../tests/tests_default.yml
  lint:
    name: ansible-lint
  log: false
  options:
    vvv: true
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - create
    - converge
    - idempotence
    - check
    - destroy
verifier:
  name: ansible
